# Site settings
title: Pim Bliek
email: pim@pimbliek.nl
description: Freelance Consultant & Adviseur  # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://pimbliek.nl" # the base hostname & protocol for your site

twitter_username: pimbliek
github_username: bliekp

# Build settings
markdown: kramdown
